## Aula 2 - Numpy

Nessa aula, iremos tratar dos seguintes conteúdos:

- NumPy
- Arrays
- Operações Matemáticas
- Alguns Métodos NumPy
- Indexação
- Máscara Booleana
- Bonus: List Comprehension

## NumPy

 A biblioteca __NumPy__ (_Numerical Python_) é um pacote do Python para a __armazenagem__ e __processamento__ de conjuntos de dados na forma __matricial__ (computação orientada por matrizes).
 
 Outras bibliotecas com o __Pandas__, __MatplotLib__ e __Scikit Learn__ dependem fortemente do __Numpy__, devido a sua eficiência computacional, sendo amplamente utilizado para __computação científica__ e __análise de dados.__
 
 O __NumPy__ é um pacote e para utilizarmos, devemos importá-lo para o nosso notebook da seguinte forma:

In [26]:
## Keras -> TensorFlow
## Seaborn -> Matplot

In [148]:
import numpy as np

## Arrays

A estrutura de dados base do __NumPy__ são os `arrays`, que funcionam de forma parecida com as listas em Python, vamos comparar semelhanças e diferenças

Diferenças:
- Todos os elementos em um array deve ser do mesmo tipo, tipicamente um tipo numérico como __float__ ou __int__
- Os arrays viabilizam a realização eficiente de operações numéricas envolvendo grandes quantidades de dados, sendo para este fim, muito mais eficientes que as listas.
- Cada dimensão de um array é chamada de eixo (_axis_)

Semelhanças:
- Os eixos são numerados a partir de $0$
- Os elementos são acessados utilizando colchetes __[]__ (semelhante às listas do Python)

#### Conversão de Listas para Arrays

Pra criar arrays a partir de uma lista, basta utilizar o procedimento **np.array():**

In [29]:
## Definir uma lista
lista = [1, 2, 3, 4, 5, 6]

## Fazendo a conversão
array = np.array(lista)

## Print comparativo
print('Lista:', lista)
print('Array', array)

Lista: [1, 2, 3, 4, 5, 6]
Array [1 2 3 4 5 6]


In [31]:
print(array[4])

5


## Operações Matemáticas entre arrays

In [32]:
## Contas com constantes
array

array([1, 2, 3, 4, 5, 6])

In [33]:
array_x2 = array * 2
print(array_x2)

[ 2  4  6  8 10 12]


In [36]:
print('Array Original:', array)
print('Soma 2 no array:', array + 2)
print('Subtrair 2 no array:', array - 2)
print('Multiplica por 2 o array:', array * 2)
print('Divide por 2 o array', array / 2)
print('Elevar a potencia de 2 o array', array ** 2)
print('Divisão inteira por 2 do array', array // 2)
print('resto da divisão por 2 do array', array % 2)
print('Inverso dos elementos do array', 1 / array)

Array Original: [1 2 3 4 5 6]
Soma 2 no array: [3 4 5 6 7 8]
Subtrair 2 no array: [-1  0  1  2  3  4]
Multiplica por 2 o array: [ 2  4  6  8 10 12]
Divide por 2 o array [0.5 1.  1.5 2.  2.5 3. ]
Elevar a potencia de 2 o array [ 1  4  9 16 25 36]
Divisão inteira por 2 do array [0 1 1 2 2 3]
resto da divisão por 2 do array [1 0 1 0 1 0]
Inverso dos elementos do array [1.         0.5        0.33333333 0.25       0.2        0.16666667]


In [40]:
## Contas entre arrays
array = np.array([1, 2, 3, 4, 5, 6])
array_2 = np.array([6, 5, 4, 3, 2, 1])

print('Soma de arrays', array + array_2)
print('Multiplicação de arrays', array * array_2)
print('Divisão de arrays', array / array_2)

Soma de arrays [7 7 7 7 7 7]
Multiplicação de arrays [ 6 10 12 12 10  6]
Divisão de arrays [0.16666667 0.4        0.75       1.33333333 2.5        6.        ]


## Exercício

Vamos fazer um exercício para dar uma revisada nos conhecimentos de python e ao mesmo tempo praticar o que aprendemos até aqui. Construa um programa onde o usuário digita uma lista de preços de produtos. Depois peça ao lojista que digite uma lista de descontos em percentagem.

De posse das duas listas, transforme ambas em Arrays NumPy e calcule a lista/array dos preços resultantes desta compra!

In [43]:
lista_produtos = []
lista_descontos = []

while (len(lista_produtos) < 5):
    preco_produto = float(input('Digite o preço do produto: '))
    lista_produtos.append(preco_produto)
    
while (len(lista_descontos) < 5):
    desconto = float(input('Digite o desconto do produto: '))
    lista_descontos.append(desconto)
    
array_produtos = np.array(lista_produtos)
array_descontos = np.array(lista_descontos)

array_descontos = array_descontos / 100
array_taxa_desconto = array_produtos * array_descontos
array_precos_corrigidos = array_produtos - array_taxa_desconto

print('Array Produtos: ', array_produtos)
print('Array Descontos: ', array_descontos)
print('Array Preços Corrigidos: ', array_precos_corrigidos)

Digite o preço do produto: 10
Digite o preço do produto: 10
Digite o preço do produto: 10
Digite o preço do produto: 10
Digite o preço do produto: 10
Digite o desconto do produto: 10
Digite o desconto do produto: 20
Digite o desconto do produto: 30
Digite o desconto do produto: 40
Digite o desconto do produto: 50
Array Produtos:  [10. 10. 10. 10. 10.]
Array Descontos:  [0.1 0.2 0.3 0.4 0.5]
Array Preços Corrigidos:  [9. 8. 7. 6. 5.]


## Alguns métodos do NumPy para criar Arrays

Outra forma de criarmos arrays seria usando __métodos NumPy__ como por exemplo __np.zeros__, __np.ones__ e outros mais:

In [44]:
## Array de Zeros
arr_zeros = np.zeros(10) # Argumento é o tamanho do array

print(arr_zeros)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [45]:
## Array de Uns
arr_ones = np.ones(10) # Argumento é o tamanho do array

print(arr_ones)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [52]:
## Revisão método range

## A função range não tem um número FIXO de argumentos
## Ela pode ter até 3 argumentos 

## Se passamos ela com um argumento só, ela começa em 0 vai até um antes do numero que passamos
## de um em um

# for i in range(10): ## É um metodo que gera uma lista de numeros
#     print(i)

## Se passamos ela com dois argumentos, ela começa no primeiro vai até um antes do 
## segundo de um em um

# for i in range(5, 10):
#     print(i)

## Se passamos ela com tres argumentos, ela começa no primeiro vai até um antes do 
## segundo com o terceiro somando em cada um
for i in range(10, 0, -1):
    print(i)

10
9
8
7
6
5
4
3
2
1


In [48]:
print(range(10)) ## Sugestão, pesquisar sobre o objeto "range"

range(0, 10)


In [53]:
## Array de Range
arr_sequencia = np.arange(10) ## arange = Array range

print(arr_sequencia)

[0 1 2 3 4 5 6 7 8 9]


In [54]:
## Com 2 argumentos
arr_range = np.arange(11, 21)

print(arr_range)

[11 12 13 14 15 16 17 18 19 20]


In [55]:
## 3 argumentos
## Quero todos os pares entre 0 e 100
arr_pares = np.arange(0, 100, 2)

print(arr_pares)

[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46
 48 50 52 54 56 58 60 62 64 66 68 70 72 74 76 78 80 82 84 86 88 90 92 94
 96 98]


In [56]:
## linspace -> Fatiamento de intervalo
arr_linspace = np.linspace(0, 1, 5)
print(arr_linspace)

[0.   0.25 0.5  0.75 1.  ]


In [57]:
## Distribuição aleatória entre 0 e 1
arr_random = np.random.rand(10)

print(arr_random)

[0.56044831 0.13050565 0.07973345 0.20980423 0.96053736 0.47197603
 0.7446965  0.27114183 0.33176009 0.24026868]


In [69]:
## Distribuição aleatoria e normal
arr_normal = np.random.normal(0, 1, 10) ## Ele trabalha com a função normal
## 3 argumentos, o primeiro é a media, o segundo é a variancia e o terceiro é a quantidade
## de elementos

print(arr_normal)

[ 0.43207303 -2.03678977  0.75769098  0.53891071 -0.14693121 -2.18222391
 -1.60108252  1.56961976 -0.72584823 -0.61347855]


In [62]:
## distribuição aleatória e inteira
arr_inteiros = np.random.randint(0, 100, 20) ## 3 Argumentos, os 2 primeiros são o
                                            ## intervalo e o 3o é quantos elementos

print(arr_inteiros)

[76 76  3 89 53 95 85 23 24 29 56 34 36 48 74 90 76 58  7 95]


## Métodos do NumPy para estatística e ordenação

In [60]:
## Método sort
arr_inteiros.sort()

In [63]:
print(arr_inteiros)

[76 76  3 89 53 95 85 23 24 29 56 34 36 48 74 90 76 58  7 95]


In [64]:
## Método argsort
indices = np.argsort(arr_inteiros)

print('Array: ', arr_inteiros)
print('Indices:', indices)

Array:  [76 76  3 89 53 95 85 23 24 29 56 34 36 48 74 90 76 58  7 95]
Indices: [ 2 18  7  8  9 11 12 13  4 10 17 14 16  0  1  6  3 15  5 19]


In [65]:
## Método max
arr_inteiros.max()

95

In [66]:
## Método min
arr_inteiros.min()

3

In [67]:
## Metodo sum
arr_inteiros.sum()

1127

In [71]:
## Metodo mean
lista_simples = [1,2,3,4,5]
arr_simples = np.array(lista_simples)
arr_simples.mean()

3.0

In [72]:
## Metodo std
arr_inteiros.std()

28.863948101394584

In [73]:
## Metodo argmax
arr_inteiros.argmax()

5

In [74]:
print(arr_inteiros)

[76 76  3 89 53 95 85 23 24 29 56 34 36 48 74 90 76 58  7 95]


In [76]:
## Metodo argmin
arr_inteiros.argmin()

2

In [101]:
arr_normal = np.random.normal(0, 1, 10000)

In [102]:
arr_normal.mean()

0.010242165176422785

In [106]:
## Também podemos arredondar um array, usando a função round
arr_random = np.random.uniform(0, 10, 20)
print(arr_random.round(2))

[7.03 7.46 0.15 2.27 5.78 3.96 0.29 1.53 9.32 3.14 4.38 3.4  9.   2.75
 8.95 5.46 8.33 3.54 0.03 4.21]


## Exercício

Mais um exercício onde queremos um pouco de revisão. Faça um programa que gera aleatóriamente as notas de 20 alunos entre 0 e 10 (notas quebradas são permitidas, um 8.4 por exemplo é uma nota válida). Em seguida, calcule a média dessa turma

In [103]:
arr_random = np.random.randint(0, 101, 20)
arr_notas = arr_random/10

print(arr_notas)

media_notas = arr_notas.mean()

print('Media das notas', media_notas.round(2))

[4.9 3.4 0.6 4.4 6.1 7.7 2.8 5.  3.8 1.7 5.6 9.4 1.9 0.7 9.3 1.4 5.  0.6
 1.5 2. ]
Media das notas 3.89


## Indexação

In [114]:
## Acesso a elemento
array = np.arange(7, 15, 1)
print('Array:', array)

## Para acessar um elemento basta passarmos colchetes e a posição dele, lembrando que começa em 0
print(array[4])

print(array[-2])

Array: [ 7  8  9 10 11 12 13 14]
11
13


In [125]:
## Array Slicing
## Funciona muito parecido com aquele range, o : é como se fosse a virgula
## O que vem antes é o começo (incluso) e o que vai depois é o final (excluido)

print('Slicing do array entre as posições 1 e 5', array[1:5])

print('Slicing do array até a posição 3', array[:3])

print('Slicing do array a partir da posição 3', array[3:])

print('Slicing do array na direção oposta', array[7:0:-2])

[7 8 9]


## Mascára Booleana

In [126]:
## Construindo uma máscara
array = np.arange(20)
print('Array: ', array)

Array:  [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [ ]:
## Booleano é um tipo de dado que representa uma conclusão lógica
## Verdadeiro ou Falso
## Comparações basicas do python

## > - maior
## < - menor
## == - igual
## != - diferente
## >= - maior ou igual
## <= - menor ou igual



In [129]:
print(array)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [133]:
## Como a máscara se parece?
mascara = array < 10
print(mascara)

[ True  True  True  True  True  True  True  True  True  True False False
 False False False False False False False False]


In [134]:
## Acessando o array com a mascara
print(array[mascara])

[0 1 2 3 4 5 6 7 8 9]


In [141]:
## Máscara composta
## Quero maior que 10 e menor que 15
mascara_composta = (array > 10) & (array < 15)
print(array[mascara_composta])

mascara_composta = (array < 5) | (array > 15)
print(array[mascara_composta])

mascara_composta = ~(array >= 10)
print(array[mascara_composta])

[11 12 13 14]
[ 0  1  2  3  4 16 17 18 19]
[0 1 2 3 4 5 6 7 8 9]


In [145]:
## Podemos usar a mascara para editar valores
mascara_composta = ~((array > 10) & (array < 15))
array[mascara_composta] = 0
print(array)

[ 0  0  0  0  0  0  0  0  0  0  0 11 12 13 14  0  0  0  0  0]


## Exercícios

1 - Faça uma máscara que identifique num array se os elementos são pares ou não

2 - Volte no exercício da lista de notas. Se a media for 7, quais deles terão passado? Use uma mascara para descobrir

3 - Quais foram acima da média de todos os alunos?

In [153]:
## 1
arr_random = np.random.randint(0, 101, 20)
print('Array:', arr_random)

mascara_par = (arr_random % 2 == 0)
print(arr_random[mascara_par])

Array: [84 75 92 74 81 90 27 42 89 71 54 48 59 32 10 76 22 61 37 53]
[84 92 74 90 42 54 48 32 10 76 22]


In [155]:
## 2
arr_random = np.random.randint(0, 101, 20)
arr_notas = arr_random/10

print('Notas:', arr_notas)

mascara_notas = arr_notas >= 7

print(arr_notas[mascara_notas])

Notas: [5.9 3.2 4.7 0.6 4.  0.2 6.5 5.7 2.7 5.9 7.4 2.5 5.9 8.4 0.3 1.1 6.7 4.1
 8.9 1.2]
[7.4 8.4 8.9]


In [164]:
## 3
media_sala = arr_notas.mean()

mascara_media = arr_notas > media_sala

print(arr_notas[mascara_media])

[5.9 4.7 6.5 5.7 5.9 7.4 5.9 8.4 6.7 8.9]


In [160]:
## Para saber as posições onde tem 1
np.argwhere(mascara_media)

array([[ 0],
       [ 2],
       [ 6],
       [ 7],
       [ 9],
       [10],
       [12],
       [13],
       [16],
       [18]], dtype=int64)

In [159]:
print(mascara_media) ## Pro python debaixo dos panos, todos os Trues = 1
## Todos os Falses = 0

[ True False  True False False False  True  True False  True  True False
  True  True False False  True False  True False]


## List Comprehension

<img src='https://miro.medium.com/max/858/0*ChFR2D9j8fxqz3D5.png' width=800>

In [162]:
even_squares = [num * num for num in range(11) if num % 2 == 0]

In [163]:
print(even_squares)

[0, 4, 16, 36, 64, 100]


In [161]:
even_squares = []
for num in range(11):
    if(num % 2 == 0):
        even_squares.append(num * num)

print(even_squares)

[0, 4, 16, 36, 64, 100]


## Exercício - Desafio

Utilize comprehension para gerar a lista de todos os números pares entre 0 e 19. Converta a lista em um __numpy__ array e cálcule a média.